vich_uploader:
  db_driver: orm
  mappings:
    film_image:
      uri_prefix: /images/films
      upload_destination: "%kernel.project_dir%/public/images/films"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
      inject_on_load: false